### PR TITLE
Update deps and fix tests

### PR DESCRIPTION
**Pull request by spirosikmd**
Hi @linasmnew! Thank you for this package! I wanted to implement a couple of fixes (for example for the [`noRetry`](https://github.com/spirosikmd/react-graceful-image/commit/e0132aac5de97e786ef141f45c8e14eb1e3faca6)), but when I try to test, the tests were breaking. I took the liberty to update few of the dependencies.

By updating the dependencies the total size of the build is now much smaller than before.

**Before**
Screen Shot 2019-05-25 at 19 14 51

**After**
Screen Shot 2019-05-25 at 19 15 48

After updating the dependencies and making a few modifications, the tests are working again.

Screen Shot 2019-05-26 at 10 33 31

There was no `yarn.lock` or `package-lock.json` file, so I added the `package-lock.json` file for now. Let me know what you think!

### CODE REVIEW

**Comment by spirosikmd** [comment]
Hey @linasmnew! Any thoughts on this PR?

**Comment by killmenot** [comment]
@linasmnew is there a chance to merge this PR?

**Comment by spirosikmd** [comment]
I will rebase as well to the latest master, to make sure changes to dependencies are covered!

**Comment by linasmnew** [comment]
Hey @spirosikmd thanks for your contribution, and sorry for the long wait.

**Comment by spirosikmd** [comment]
@linasmnew thank you for merging! I will create a fix for the no retry functionality 🎉

**Pull request merged**
